# 模型配置文件
# YOLOv8 配置

# 模型架构
model:
  backbone: yolov8n  # 使用YOLOv8-nano作为基础模型
  
# 训练参数
train:
  epochs: 100
  batch_size: 16
  img_size: 640
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  
# 数据增强
augmentation:
  hsv_h: 0.015  # HSV色调增强
  hsv_s: 0.7    # HSV饱和度增强
  hsv_v: 0.4    # HSV亮度增强
  degrees: 0.0   # 旋转角度
  translate: 0.1 # 平移
  scale: 0.5    # 缩放
  shear: 0.0    # 剪切
  perspective: 0.0 # 透视变换
  flipud: 0.0   # 上下翻转
  fliplr: 0.5   # 左右翻转
  mosaic: 1.0   # 马赛克增强
  mixup: 0.0    # 混合增强
  
# 损失函数权重
loss:
  box: 0.05     # 边界框损失权重
  cls: 0.5      # 分类损失权重
  dfl: 1.0      # DFL损失权重
  
# 优化器
optimizer:
  type: SGD     # 优化器类型
  lr0: 0.01     # 初始学习率
  lrf: 0.01     # 最终学习率
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
